### ISSUE TITLE
Cannot get 

### ISSUE THREAD

**Issue by pauldsmyth** [ThibaultLaurens/aws-dashing#3]
Is it possible to get this working with the standard dashing.io package rather than writing something for dashing then porting it to node.js? Cannot get past this:

module.js:328
    throw err;
    ^

Error: Cannot find module 'dashing-js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/super/aws-dashing/server.js:1:77)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by pauldsmyth** [comment]
Assuming this is abandonware. Shame really, doing it this way so that none of the dozens of other dashboards will work without conversion, Not Invented Here syndrome personified.

**Comment by RobWhyte91** [comment]
@pauldsmyth Did you get this working or find a good alternative?
